version: '3.8'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./web/:/app
    command: "go test ./src/tests"
    env_file: ./example.env
    depends_on:
      - neo
  
  neo:
    image: neo4j:5.5.0
    ports:
      - "7474:7474"  # Browser UI
      - "7687:7687"  # Bolt protocol (used by drivers)
    env_file: ./example.env
